import type { Metadata } from "next";
import { Syne, Poppins } from "next/font/google";
import { EditorProvider } from "@/context/EditorContext";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const syne = Syne({
    variable: "--font-syne",
    subsets: ["latin"],
    display: "swap",
});

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800"],
    display: "swap",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${poppins.variable} ${syne.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col overflow-x-hidden">
                {
                    <EditorProvider>
                        {/* Navigation */}
                        <Navbar />
                        {children}
                    </EditorProvider>
                }
            </body>
        </html>
    );
}
